apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-warehouseapi
  name: deploy-warehouseapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-warehouseapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-warehouseapi
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/avid-phoenix-433407-v0/python-repo/warehouseapi:amd64
        name: warehouseapi
        resources: {}
status: {}
