apiVersion: v1
kind: Service
metadata:
  name: service-warehouseapi
  labels:
    job: node-warehouseapi
    app: service-warehouseapi
spec:
  type: NodePort
  selector:
    app: deploy-warehouseapi
  ports:
    - name: web
      protocol: TCP
      port: 6789
      targetPort: 6789
      nodePort: 30001